// Superficie pública de adapters/db. El cliente (obtenerDb) no se reexporta a propósito; solo las
// pruebas lo importan directamente desde ./cliente.js para preparar y limpiar datos.
export {
  cerrarConexion,
  ejecutorSqlDe,
  inicializarDb,
  type Ejecutor,
  type EjecutorSql,
} from "./cliente.js"
export { verificarConexion } from "./salud.js"
export {
  actualizarContrasenaYRevocarSesiones,
  buscarAdmin,
  buscarCredencialesPorEmail,
  buscarCredencialesPorId,
  buscarCuentaPorEmail,
  buscarCuentaPorId,
  buscarPerfilPorId,
  cambiarContrasenaPropia,
  corregirCorreo,
  crearMaestroInvitado,
  crearUsuario,
  crearUsuarioConSesion,
  existeAdmin,
  restablecerConTemporal,
  type CredencialesDeUsuario,
  type NuevaSesionDeUsuario,
  type NuevoMaestroInvitado,
  type NuevoUsuario,
  type UsuarioAdmin,
} from "./usuarios.js"
export {
  buscarEnlacePorHash,
  buscarEnlacePorId,
  crearEnlaceRegistro,
  listarEnlacesRegistro,
  listarRegistradosPorEnlace,
  registrarMaestroConEnlace,
  revocarEnlaceRegistro,
  type EnlaceRegistroConRegistrados,
  type EnlaceRegistroDb,
  type ListaEnlacesDb,
  type ListaRegistradosDb,
  type RegistradoDb,
} from "./enlaces-registro.js"
export {
  buscarSesionPorHash,
  crearSesion,
  revocarSesion,
  revocarSesionPorHash,
  revocarTodasLasSesiones,
  rotarSesion,
  type DatosDeSesion,
  type SesionEncontrada,
} from "./sesiones.js"
export {
  buscarInvitacionPorHash,
  buscarTokenParaEnvio,
  buscarTokenPorHash,
  contarRecuperacionesRecientes,
  prepararTokenDeRecuperacion,
  usarTokenYCambiarContrasena,
  type InvitacionParaUso,
  type TokenParaEnvio,
  type TokenParaUso,
} from "./tokens-cuenta.js"
export {
  CLAVE_BLOQUEO_INVITACIONES_EN_LOTE,
  invitarMaestrosEnLote,
  type CandidatoParaInvitarEnLote,
  type ResultadoInvitacionEnLote,
} from "./invitaciones.js"
export {
  buscarClasePorCodigo,
  buscarDatosDePertenencia,
  crearClaseAdministrada,
  editarClase,
  inscribir,
  leerClase,
  leerCodigo,
  listarClasesAdmin,
  listarClasesImpartidas,
  listarClasesInscritas,
  ORDEN_DE_MAESTROS,
  regenerarCodigo,
  type ClaseAdminDb,
  type ClaseDb,
  type DatosDePertenencia,
  type ListaClasesAdminDb,
  type ListaClasesImpartidasDb,
  type ListaClasesInscritasDb,
  type MaestroDb,
} from "./clases.js"
export {
  asignarMaestro,
  buscarMaestrosCandidatos,
  retirarMaestro,
  type CandidatoMaestroDb,
  type ListaCandidatosMaestroDb,
  type MaestrosDeClaseDb,
} from "./maestros-de-clase.js"
export {
  agregarAlumnoManual,
  buscarCandidatos,
  listarAlumnosDeClase,
  listarPersonas,
  quitarAlumno,
  type AlumnoDeClaseDb,
  type CandidatoDb,
  type ListaAlumnosDeClaseDb,
  type ListaCandidatosDb,
  type ListaPersonasDb,
  type PersonaDb,
} from "./inscripciones.js"
export {
  buscarArchivoConfirmado,
  buscarArchivosParaConfirmar,
  registrarArchivoPendiente,
  type ArchivoDb,
} from "./archivos.js"
export {
  borrarComentario,
  borrarMiComentario,
  borrarPublicacion,
  crearComentario,
  crearPublicacion,
  listarComentarios,
  listarPublicaciones,
  type AutorDb,
  type ComentarioDb,
  type ListaComentariosDb,
  type ListaPublicacionesDb,
  type PublicacionDb,
} from "./publicaciones.js"
